nodejs-hw02-express
Oleksandra83/nodejs-homework-rest-api pull request #1
Opened 2023-08-25 16:50 UTC by Oleksandra83

Перевірте будь ласка

2023-08-25 17:11 UTC, KhYulian commented on decorators/ctrlWrapper.js
> +	return func;
```suggestion
	return async (req, res, next) => {
		try {
			await ctrl(req, res, next);
		} catch (error) {
			next(error);
		}
	};
```

2023-08-25 17:11 UTC, KhYulian commented on helpers/HttpError.js
> +};
Використовуйте класи https://javascript.info/custom-errors

2023-08-25 17:12 UTC, KhYulian commented on schemas/contacts-schemas.js
utils/validation/...

2023-08-25 17:12 UTC, KhYulian requested changes
залишив коменти

2023-08-25 17:46 UTC, Oleksandra83 commented
виправила всі зауваження

2023-08-26 05:02 UTC, KhYulian approved these changes
Чудова робота)

2023-08-26 05:02 UTC, merged